print("How old are you?")
age = input('Enter Your Age : ')
print("How tall are you?")
height = input('Enter Your Height : ')
print("How much do you weight?")
weight = input('Enter Your Weight : ')
print("So, you're %r old, %r tall and %r heavy." % (age, height, weight))
